/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

import dao.UsersDao;
import model.Users;

public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form SignupPage
     */
    public static Users currentUser = null;

    public LoginPage() {
        initComponents();
    }

    public Boolean validateLoginDetails() {
        boolean isValidate;
        String name = txt_username.getText();
        String password = String.valueOf(txt_password.getPassword());

        if (name.isEmpty()) {

            checkErrorLabel.setText("*Please fill username");
            isValidate = false;
        } else if (password.isEmpty()) {
            checkErrorLabel.setText("*Please fill password");
            isValidate = false;
        } else {
            checkErrorLabel.setText(" ");
            isValidate = true;
        }

        return isValidate;
    }

    public void login() {
        String name = txt_username.getText();
        String password = String.valueOf(txt_password.getPassword());
        UsersDao ud = new UsersDao();
        Users user = ud.userLogin(name, password);
        if (user == null) {
            checkErrorLabel.setText("*Invalid username or password");
        } else {
            LoginPage.currentUser = user;
            JOptionPane.showMessageDialog(LoginPage.this, "Login Successful");
            HomePage home = new HomePage();
            home.setVisible(true);
            this.dispose();
        }
    }

    /**
     * {
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginButton = new rojerusan.RSMaterialButtonRectangle();
        createAccountButton = new rojerusan.RSMaterialButtonRectangle();
        txt_username = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        checkErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(900, 740));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo (Custom).png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banner.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("DVN-Poppins", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 36, 36));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hey, hello!!");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, -1));

        jLabel3.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 36, 36));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome back here!");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 500, -1));

        jLabel4.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 36, 36));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 90, -1));

        loginButton.setBackground(new java.awt.Color(247, 171, 10));
        loginButton.setText("Login");
        loginButton.setFont(new java.awt.Font("DVN-Poppins", 1, 18)); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 350, 60));

        createAccountButton.setBackground(new java.awt.Color(245, 246, 241));
        createAccountButton.setForeground(new java.awt.Color(36, 36, 36));
        createAccountButton.setText("SignUp");
        createAccountButton.setFont(new java.awt.Font("DVN-Poppins", 1, 18)); // NOI18N
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });
        jPanel2.add(createAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 350, 60));

        txt_username.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(247, 171, 10)));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 350, 40));

        usernameLabel1.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(36, 36, 36));
        usernameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel1.setText("Username");
        jPanel2.add(usernameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 100, -1));

        jLabel5.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 36, 36));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 32, 32));

        jLabel7.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 36, 36));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/padlock.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 32, 32));

        txt_password.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(247, 171, 10)));
        txt_password.setMargin(new java.awt.Insets(2, 12, 2, 12));
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 350, 40));

        checkErrorLabel.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        checkErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        checkErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        checkErrorLabel.setText(" ");
        jPanel2.add(checkErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 350, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 500, 700));

        setSize(new java.awt.Dimension(916, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginButtonActionPerformed
        if (validateLoginDetails()) {
            login();
        }
    }// GEN-LAST:event_loginButtonActionPerformed

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txt_passwordFocusLost
        validateLoginDetails();
    }// GEN-LAST:event_txt_passwordFocusLost

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createAccountButtonActionPerformed
        // TODO add your handling code here:
        SignupPage signup = new SignupPage();
        signup.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_createAccountButtonActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txt_usernameFocusLost
        validateLoginDetails();
    }// GEN-LAST:event_txt_usernameFocusLost

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkErrorLabel;
    private rojerusan.RSMaterialButtonRectangle createAccountButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonRectangle loginButton;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
