/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package components;

import dao.DBConnection;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author winlax
 */
public class HomePage extends javax.swing.JInternalFrame {

    /**
     * Creates new form HomePageData
     */
    String book_name, author, student_name, branch, year, status;
    int book_id, quantity, student_id, issue_id;
    Date issue_date, due_date;

    public HomePage() {
        initComponents();
        // set border null
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        setStudentDetailToTable();
        setBookDetailToTable();
        setStatusBookDetails();
//        setIssueBookDetails();
    }

    public void setStudentDetailToTable() {
        // connect to database
        int countStudent = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from student_details");
            while (rs.next()) {
                countStudent++;
                // student_id = rs.getInt("student_id");
                // student_name = rs.getString("student_name");
                // branch = rs.getString("branch");
                // year = rs.getString("year");
                // DefaultTableModel model = (DefaultTableModel) tableStudent.getModel();
                // model.addRow(new Object[] { student_id, student_name, branch, year });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        countStudentLabel.setText(" " + String.valueOf(countStudent));
    }

    public void setBookDetailToTable() {
        // connect to database
        int countBook = 0;
        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM book_details");
            while (rs.next()) {
                countBook++;
                // book_id = rs.getInt("book_id");
                // book_name = rs.getString("book_name");
                // author = rs.getString("author");
                // quantity = rs.getInt("quantity");
                // DefaultTableModel model = (DefaultTableModel) tableBook.getModel();
                // model.addRow(new Object[] { book_id, book_name, author, quantity });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        countBookLabel.setText(" " + String.valueOf(countBook));
    }

    public void setStatusBookDetails() {
        int countPending = 0;
        int countReturn = 0;
        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM issue_book_details where status='Pending'");
            while (rs.next()) {
                countPending++;
            }
            ResultSet rs1 = st.executeQuery("SELECT * FROM issue_book_details where status='Returned'");
            while (rs1.next()) {
                countReturn++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        countPendingLabel.setText(" " + String.valueOf(countPending));
        countReturnLabel.setText(" " + String.valueOf(countReturn));
    }

   public void setIssueBookDetails() {
       try {
           

       } catch (Exception e) {
           e.printStackTrace();
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        panelBorder4 = new components.PanelBorder();
        countReturnLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panelBorder3 = new components.PanelBorder();
        countPendingLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelBorder2 = new components.PanelBorder();
        countStudentLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelBorder1 = new components.PanelBorder();
        countBookLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelBorder5 = new components.PanelBorder();
        jLabel16 = new javax.swing.JLabel();
        panelBorder7 = new components.PanelBorder();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        topBooksTable = new rojeru_san.complementos.RSTableMetro();
        panelBorder6 = new components.PanelBorder();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        studentBooksCountTable = new rojeru_san.complementos.RSTableMetro();
        panelBorder8 = new components.PanelBorder();
        jScrollPane6 = new javax.swing.JScrollPane();
        issueBookDetailsTable = new rojeru_san.complementos.RSTableMetro();
        jLabel26 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setFocusable(false);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(950, 730));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        kGradientPanel2.setFont(new java.awt.Font("DVN-Poppins", 0, 14)); // NOI18N
        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(245, 246, 241));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(950, 730));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder4.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countReturnLabel.setFont(new java.awt.Font("DVN-Poppins", 1, 40)); // NOI18N
        countReturnLabel.setForeground(new java.awt.Color(36, 36, 36));
        countReturnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/return.png"))); // NOI18N
        countReturnLabel.setText("   100");
        panelBorder4.add(countReturnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("DVN-Poppins", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Return books");
        panelBorder4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        kGradientPanel2.add(panelBorder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 210, 110));

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countPendingLabel.setFont(new java.awt.Font("DVN-Poppins", 1, 40)); // NOI18N
        countPendingLabel.setForeground(new java.awt.Color(36, 36, 36));
        countPendingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pending.png"))); // NOI18N
        countPendingLabel.setText("   100");
        panelBorder3.add(countPendingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel19.setFont(new java.awt.Font("DVN-Poppins", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Pending books");
        panelBorder3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        kGradientPanel2.add(panelBorder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 210, 110));

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countStudentLabel.setFont(new java.awt.Font("DVN-Poppins", 1, 40)); // NOI18N
        countStudentLabel.setForeground(new java.awt.Color(36, 36, 36));
        countStudentLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/member.png"))); // NOI18N
        countStudentLabel.setText("   100");
        panelBorder2.add(countStudentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel17.setFont(new java.awt.Font("DVN-Poppins", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Students");
        panelBorder2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        kGradientPanel2.add(panelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 210, 110));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countBookLabel.setFont(new java.awt.Font("DVN-Poppins", 1, 40)); // NOI18N
        countBookLabel.setForeground(new java.awt.Color(36, 36, 36));
        countBookLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book.png"))); // NOI18N
        countBookLabel.setText("   100");
        panelBorder1.add(countBookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("DVN-Poppins", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Total books");
        panelBorder1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        kGradientPanel2.add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 110));

        panelBorder5.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("DVN-Poppins", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Total books");
        panelBorder5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        kGradientPanel2.add(panelBorder5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 560, 320));

        panelBorder7.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("DVN-Poppins", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Top Books");
        panelBorder7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, -1));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(null);
        jScrollPane5.setForeground(new java.awt.Color(255, 255, 255));

        topBooksTable.setForeground(new java.awt.Color(255, 255, 255));
        topBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        topBooksTable.setToolTipText("");
        topBooksTable.setAlignmentX(0.0F);
        topBooksTable.setAlignmentY(0.0F);
        topBooksTable.setAltoHead(0);
        topBooksTable.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        topBooksTable.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        topBooksTable.setColorBordeHead(new java.awt.Color(255, 255, 255));
        topBooksTable.setColorFilasBackgound1(new java.awt.Color(245, 246, 241));
        topBooksTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        topBooksTable.setColorFilasForeground1(new java.awt.Color(36, 36, 36));
        topBooksTable.setColorFilasForeground2(new java.awt.Color(36, 36, 36));
        topBooksTable.setColorForegroundHead(new java.awt.Color(36, 36, 36));
        topBooksTable.setColorSelBackgound(new java.awt.Color(255, 204, 204));
        topBooksTable.setColorSelForeground(new java.awt.Color(36, 36, 36));
        topBooksTable.setDragEnabled(true);
        topBooksTable.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        topBooksTable.setFuenteFilas(new java.awt.Font("DVN-Poppins", 0, 14)); // NOI18N
        topBooksTable.setFuenteFilasSelect(new java.awt.Font("DVN-Poppins", 1, 14)); // NOI18N
        topBooksTable.setFuenteHead(new java.awt.Font("DVN-Poppins", 0, 14)); // NOI18N
        topBooksTable.setGridColor(new java.awt.Color(255, 255, 255));
        topBooksTable.setRowHeight(50);
        topBooksTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        topBooksTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        topBooksTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(topBooksTable);
        if (topBooksTable.getColumnModel().getColumnCount() > 0) {
            topBooksTable.getColumnModel().getColumn(1).setMinWidth(30);
            topBooksTable.getColumnModel().getColumn(1).setMaxWidth(30);
        }

        panelBorder7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 150));

        kGradientPanel2.add(panelBorder7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 320, 220));

        panelBorder6.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("DVN-Poppins", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Students books count");
        panelBorder6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, -1));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));

        studentBooksCountTable.setForeground(new java.awt.Color(255, 255, 255));
        studentBooksCountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Book Name", "Count"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentBooksCountTable.setToolTipText("");
        studentBooksCountTable.setAlignmentX(0.0F);
        studentBooksCountTable.setAlignmentY(0.0F);
        studentBooksCountTable.setAltoHead(30);
        studentBooksCountTable.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        studentBooksCountTable.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        studentBooksCountTable.setColorBordeHead(new java.awt.Color(255, 255, 255));
        studentBooksCountTable.setColorFilasBackgound1(new java.awt.Color(245, 246, 241));
        studentBooksCountTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        studentBooksCountTable.setColorFilasForeground1(new java.awt.Color(36, 36, 36));
        studentBooksCountTable.setColorFilasForeground2(new java.awt.Color(36, 36, 36));
        studentBooksCountTable.setColorForegroundHead(new java.awt.Color(36, 36, 36));
        studentBooksCountTable.setColorSelBackgound(new java.awt.Color(255, 204, 204));
        studentBooksCountTable.setColorSelForeground(new java.awt.Color(36, 36, 36));
        studentBooksCountTable.setDragEnabled(true);
        studentBooksCountTable.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        studentBooksCountTable.setFuenteFilas(new java.awt.Font("DVN-Poppins", 0, 14)); // NOI18N
        studentBooksCountTable.setFuenteFilasSelect(new java.awt.Font("DVN-Poppins", 1, 14)); // NOI18N
        studentBooksCountTable.setFuenteHead(new java.awt.Font("DVN-Poppins", 0, 14)); // NOI18N
        studentBooksCountTable.setGridColor(new java.awt.Color(255, 255, 255));
        studentBooksCountTable.setRowHeight(46);
        studentBooksCountTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        studentBooksCountTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        studentBooksCountTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(studentBooksCountTable);
        if (studentBooksCountTable.getColumnModel().getColumnCount() > 0) {
            studentBooksCountTable.getColumnModel().getColumn(1).setMinWidth(50);
            studentBooksCountTable.getColumnModel().getColumn(1).setMaxWidth(50);
        }

        panelBorder6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 280, 260));

        kGradientPanel2.add(panelBorder6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 320, 320));

        panelBorder8.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);
        jScrollPane6.setForeground(new java.awt.Color(255, 255, 255));

        issueBookDetailsTable.setForeground(new java.awt.Color(255, 255, 255));
        issueBookDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Name", "Student Name", "Issue Date", "Due Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        issueBookDetailsTable.setToolTipText("");
        issueBookDetailsTable.setAlignmentX(0.0F);
        issueBookDetailsTable.setAlignmentY(0.0F);
        issueBookDetailsTable.setAltoHead(30);
        issueBookDetailsTable.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        issueBookDetailsTable.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        issueBookDetailsTable.setColorBordeHead(new java.awt.Color(255, 255, 255));
        issueBookDetailsTable.setColorFilasBackgound1(new java.awt.Color(245, 246, 241));
        issueBookDetailsTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        issueBookDetailsTable.setColorFilasForeground1(new java.awt.Color(36, 36, 36));
        issueBookDetailsTable.setColorFilasForeground2(new java.awt.Color(36, 36, 36));
        issueBookDetailsTable.setColorForegroundHead(new java.awt.Color(36, 36, 36));
        issueBookDetailsTable.setColorSelBackgound(new java.awt.Color(255, 204, 204));
        issueBookDetailsTable.setColorSelForeground(new java.awt.Color(36, 36, 36));
        issueBookDetailsTable.setDragEnabled(true);
        issueBookDetailsTable.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        issueBookDetailsTable.setFuenteFilas(new java.awt.Font("DVN-Poppins", 0, 14)); // NOI18N
        issueBookDetailsTable.setFuenteFilasSelect(new java.awt.Font("DVN-Poppins", 1, 14)); // NOI18N
        issueBookDetailsTable.setFuenteHead(new java.awt.Font("DVN-Poppins", 0, 14)); // NOI18N
        issueBookDetailsTable.setGridColor(new java.awt.Color(255, 255, 255));
        issueBookDetailsTable.setRowHeight(34);
        issueBookDetailsTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        issueBookDetailsTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        issueBookDetailsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(issueBookDetailsTable);
        if (issueBookDetailsTable.getColumnModel().getColumnCount() > 0) {
            issueBookDetailsTable.getColumnModel().getColumn(0).setMinWidth(65);
            issueBookDetailsTable.getColumnModel().getColumn(0).setMaxWidth(65);
        }

        panelBorder8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 510, 150));

        jLabel26.setBackground(new java.awt.Color(36, 36, 36));
        jLabel26.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Issue List");
        panelBorder8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        kGradientPanel2.add(panelBorder8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 560, 220));

        getContentPane().add(kGradientPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seeMoreViewIssueBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_seeMoreViewIssueBooksButtonActionPerformed
        // TODO add your handling code here:
        // IssueBook ib = new IssueBook();
        // ib.setVisible(true);
        // dispose();
    }// GEN-LAST:event_seeMoreViewIssueBooksButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countBookLabel;
    private javax.swing.JLabel countPendingLabel;
    private javax.swing.JLabel countReturnLabel;
    private javax.swing.JLabel countStudentLabel;
    private rojeru_san.complementos.RSTableMetro issueBookDetailsTable;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private components.PanelBorder panelBorder1;
    private components.PanelBorder panelBorder2;
    private components.PanelBorder panelBorder3;
    private components.PanelBorder panelBorder4;
    private components.PanelBorder panelBorder5;
    private components.PanelBorder panelBorder6;
    private components.PanelBorder panelBorder7;
    private components.PanelBorder panelBorder8;
    private rojeru_san.complementos.RSTableMetro studentBooksCountTable;
    private rojeru_san.complementos.RSTableMetro topBooksTable;
    // End of variables declaration//GEN-END:variables
}
