/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.DBConnection;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

public class SignupPage extends javax.swing.JFrame {

    /**
     * Creates new form SignupPage
     */
    public SignupPage() {
        initComponents();
        initMoving(this);
    }

    private int xMouse;
    private int yMouse;

    public void initMoving(JFrame fram) {
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                xMouse = me.getX();
                yMouse = me.getY();
            }
        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                fram.setLocation(me.getXOnScreen() - xMouse, me.getYOnScreen() - yMouse);
            }
        });
    }

    public void insertSignupDetails() {
        String name = txt_username.getText();
        String password = txt_password.getText();
        String email = txt_email.getText();
        String contact = txt_contact.getText();

        try {
            Connection con = DBConnection.getConnection();
            String sql = "insert into users(name, password, email, contact) values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, name);
            pst.setString(2, password);
            pst.setString(3, email);
            pst.setString(4, contact);
            int updateRowCount = pst.executeUpdate();
            if (updateRowCount > 0) {
                JOptionPane.showMessageDialog(this, "Signup successful");
            } else {
                JOptionPane.showMessageDialog(this, "Signup failed");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Boolean validateSignupDetails() {
        String name = txt_username.getText();
        String password = txt_password.getText();
        String contact = txt_contact.getText();

        if (name.isEmpty() || password.isEmpty() || contact.isEmpty()) {
            checkErrorLabel.setText("*Please enter valid details");
            return false;
        } else {
            checkErrorLabel.setText(" ");
            return true;
        }
    }

    public Boolean isEmail() {
        String email = txt_email.getText();
        boolean isEmail = true;
        if (email.isEmpty() || !email.matches("^.+@.+\\..+$")) {
            isEmail = false;
        }
        return isEmail;
    }

    public Boolean isDuplicateUser() {
        String name = txt_username.getText();
        boolean isDuplicate = false;
        try {
            Connection con = DBConnection.getConnection();
            String sql = "select * from users where name=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, name);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                isDuplicate = true;
            } else {
                isDuplicate = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isDuplicate;
    }

    /**
     * {
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rojerusan.RSMaterialButtonRectangle loginButton = new rojerusan.RSMaterialButtonRectangle();
        createAccountButton = new rojerusan.RSMaterialButtonRectangle();
        txt_contact = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();
        checkErrorLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo (Custom).png"))); // NOI18N
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banner.png"))); // NOI18N
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 36, 36));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/phone.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 32, 32));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("DVN-Poppins", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 36, 36));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create new account");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 500, -1));

        jLabel3.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 36, 36));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Let create new account!!");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 500, -1));

        jLabel4.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 36, 36));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 350, -1));

        emailLabel.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 0, 0));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText(" ");
        kGradientPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 200, -1));

        jLabel8.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 36, 36));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Email");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 80, -1));

        jLabel10.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 36, 36));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Contact");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 350, -1));

        loginButton.setBackground(new java.awt.Color(245, 246, 241));
        loginButton.setForeground(new java.awt.Color(36, 36, 36));
        loginButton.setText("Login");
        loginButton.setFont(new java.awt.Font("DVN-Poppins", 1, 18)); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 350, 60));

        createAccountButton.setBackground(new java.awt.Color(247, 171, 10));
        createAccountButton.setText("SignUp");
        createAccountButton.setFont(new java.awt.Font("DVN-Poppins", 1, 18)); // NOI18N
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(createAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 350, 60));

        txt_contact.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        txt_contact
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(247, 171, 10)));
        kGradientPanel1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 350, 40));

        txt_username.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        txt_username
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(247, 171, 10)));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        kGradientPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 350, 40));

        txt_password.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        txt_password
                .setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(247, 171, 10)));
        kGradientPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 350, 40));

        txt_email.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(247, 171, 10)));
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        kGradientPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 350, 40));

        usernameLabel1.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(36, 36, 36));
        usernameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel1.setText("Username");
        kGradientPanel1.add(usernameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 100, -1));

        checkErrorLabel.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        checkErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        checkErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        checkErrorLabel.setText(" ");
        kGradientPanel1.add(checkErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 350, -1));

        usernameLabel.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 0, 0));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameLabel.setText(" ");
        kGradientPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 200, -1));

        jLabel5.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 36, 36));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 32, 32));

        jLabel7.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 36, 36));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/padlock.png"))); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 32, 32));

        jLabel9.setFont(new java.awt.Font("DVN-Poppins", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 36, 36));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/email.png"))); // NOI18N
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 32, 32));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        kGradientPanel1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        getContentPane().add(kGradientPanel1);

        setSize(new java.awt.Dimension(900, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }// GEN-LAST:event_closeButtonMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginButtonActionPerformed
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();

    }// GEN-LAST:event_loginButtonActionPerformed

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {
        if (isEmail() == false) {
            emailLabel.setText("*email error");
        } else {
            emailLabel.setText(" ");
        }
    }// GEN-LAST:event_txt_emailFocusLost

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txt_usernameFocusLost
        if (isDuplicateUser() == true) {
            usernameLabel.setText("*already exists");
        } else {
            usernameLabel.setText(" ");
        }
    }// GEN-LAST:event_txt_usernameFocusLost

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createAccountButtonActionPerformed
        if (validateSignupDetails() == true && isDuplicateUser() == false && isEmail() == true) {
            insertSignupDetails();
            LoginPage login = new LoginPage();
            login.setVisible(true);
            this.dispose();
        } else {
            checkErrorLabel.setText("*Please enter valid details");
        }
    }// GEN-LAST:event_createAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkErrorLabel;
    private javax.swing.JLabel closeButton;
    private rojerusan.RSMaterialButtonRectangle createAccountButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
